import bcrypt from 'bcryptjs';
const data = {
  users: [
    {
      name: 'Nasim',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Anwari',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      //_id: '1',
      name: 'Mavi Erkek Siyah Tişört',
      slug: 'mavi-slim-shirt',
      category: 'Tişört',
      image: '/images/p1.jpg', // 679px × 829px
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'Mavi nin Erkek Koleksiyonundan Mavi Logo Baskılı Siyah Tişört Normal Kesim Kısa Kol Model Ölçüleri: Boy 187 cm Kalça: 95 cm Model Üzerindeki Ürün Bedeni Jeanler İçin, Bel: 30 Boy: 32 Diğer Ürünlerde: L Materiel:%100 Pamuk Season:21ILK2 Gender:Erkek Sleeve:Kısa Kol Fit:Normal Kesim',
    },
    {
      //_id: '2',
      name: 'Adidas Fit Shirt',
      slug: 'adidas-fit-shirt',
      category: 'Shirts',
      image: '/images/p2.jpg',
      price: 250,
      countInStock: 0,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      //_id: '3',
      name: 'Nike Slim Pant',
      slug: 'nike-slim-pant',
      category: 'Pants',
      image: '/images/p3.jpg',
      price: 25,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
    // _id: '4',
      name: 'Levis Siyah Jean',
      slug: 'Levis Siyah Jean',
      category: 'Pantolon',
      image: '/images/p4.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Levis',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
  ],
};
export default data;